name = "r2-explorer"
compatibility_date = "2024-11-06"
main = "src/index.ts"
assets = { directory = "node_modules/r2-explorer/dashboard", binding = "ASSETS", html_handling = "auto-trailing-slash", not_found_handling = "single-page-application" }
account_id="6ce0f3a43d1ab9efef4462a008a71c50"
# Bind R2 Buckets to your application.
# Docs: https://r2explorer.com/getting-started/add-r2-buckets/
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "bucket"
